# Generated by Django 3.2.15 on 2022-09-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
