# Generated by Django 3.2.15 on 2022-09-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhaar',
            old_name='aadhaar_number_hash',
            new_name='hash',
        ),
    ]
