# Generated by Django 3.2.15 on 2022-09-15 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipfs', '0002_rename_aadhaar_number_hash_aadhaar_hash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aadhaar',
            new_name='File_Upload',
        ),
    ]
